version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "./var/db_data:/db_data"
      - "./assets/data:/assets/data"
      - "./scripts:/scripts"
      - "./node_modules:/node_modules"
    networks:
      - app-network
  nuxt:
    build:
      context: .
      dockerfile: docker/${ENV}/Dockerfile
    container_name: nuxt
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/app
networks:
  app-network:
    driver: bridge
